=begin
#@ledge/external-api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

# Common files
require 'ledge_ruby_api_client/api_client'
require 'ledge_ruby_api_client/api_error'
require 'ledge_ruby_api_client/version'
require 'ledge_ruby_api_client/configuration'

# Models
require 'ledge_ruby_api_client/models/activity_type'
require 'ledge_ruby_api_client/models/create_goal_request'
require 'ledge_ruby_api_client/models/create_quest_request'
require 'ledge_ruby_api_client/models/create_quest_schedule200_response'
require 'ledge_ruby_api_client/models/create_quest_schedule_request'
require 'ledge_ruby_api_client/models/error_response'
require 'ledge_ruby_api_client/models/external_activity'
require 'ledge_ruby_api_client/models/external_user'
require 'ledge_ruby_api_client/models/gender'
require 'ledge_ruby_api_client/models/goal'
require 'ledge_ruby_api_client/models/quest'
require 'ledge_ruby_api_client/models/quest_schedule'
require 'ledge_ruby_api_client/models/quest_type'
require 'ledge_ruby_api_client/models/track_activity200_response'
require 'ledge_ruby_api_client/models/user'

# APIs
require 'ledge_ruby_api_client/api/external_api'

module LedgeApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   LedgeApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
