=begin
#@ledge/external-api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LedgeApiClient::Gender
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LedgeApiClient::Gender do
  let(:instance) { LedgeApiClient::Gender.new }

  describe 'test an instance of Gender' do
    it 'should create an instance of Gender' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LedgeApiClient::Gender)
    end
  end

end
