=begin
#@ledge/external-api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LedgeApiClient::TrackActivity200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LedgeApiClient::TrackActivity200Response do
  let(:instance) { LedgeApiClient::TrackActivity200Response.new }

  describe 'test an instance of TrackActivity200Response' do
    it 'should create an instance of TrackActivity200Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LedgeApiClient::TrackActivity200Response)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
