name: Build and Publish Ruby API Client

on:
  pull_request: #testing
  workflow_dispatch:
    branches: [main]

  release:
    types: [published]

env:
  SOURCE_PATH: ./api
  REPO_ID: github
  REPO_URL: https://rubygems.pkg.github.com/ledgelabs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build gem
        # Commands taken from jstastny/publish-gem-to-github
        run: |
          cd "${GITHUB_WORKSPACE}" || exit 1
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          echo "Setting up access to GitHub Package Registry"
          mkdir -p ~/.gem
          touch ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          echo ":github: Bearer ${{ secrets.GENERATE_API_CLIENT_TOKEN }}" >> ~/.gem/credentials

          cd ${{ env.SOURCE_PATH }}

          echo "Building the gem"
          find . -name '*.gemspec' -maxdepth 1 -exec gem build {} \;

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Publish gem

        run: |
          cd ${{ env.SOURCE_PATH }}
          echo "Pushing the built gem to GitHub Package Registry"
          find . -name '*.gem' -maxdepth 1 -print0 | xargs -0 gem push --key github --host ${{ env.REPO_URL }}
